resolver: lts-13.11

packages:
- ../../SVGFont.hs/
- card/
- sgml/
- cockatricize/
- imagine/
- boost/

extra-deps:
- txt-0.0.3.0
- git: https://github.com/strake/bytestring.hs
  commit: 5923bb9af468c86564f444b8150309995cda1132
- git: https://github.com/strake/vector.hs
  commit: 32757f1624fee4967887cbe70491d31f69fbad48
